suppressPackageStartupMessages({library(dplyr); library(readr)})
repo_root <- "c:/ReposGitHub/Chapter3_RPEUP"
source(file.path(repo_root, "paper/Version7/audits/granger_canonicalization/phase9e_conditional_partition/phase9e_conditional_partition.R"))

cat("\n=======================================================\n")
cat("EXACT PHASE 9E ESTIMATOR FOR SYSTEM 1 AT k=4\n")
cat("=======================================================\n")
# System 1: vars = pi_t, g_H. sample = df_full. k = 4.
est_s1_pi_to_gH <- run_conditional_granger_var(df_full, c("pi_t", "g_H"), "pi_t", "g_H", 4)
print(est_s1_pi_to_gH)
est_s1_gH_to_pi <- run_conditional_granger_var(df_full, c("pi_t", "g_H"), "g_H", "pi_t", 4)
print(est_s1_gH_to_pi)

cat("\n=======================================================\n")
cat("EXACT PHASE 9E ESTIMATOR FOR SYSTEM 2 AT k=3\n")
cat("=======================================================\n")
# System 2: vars = pi_t, g_M1, g_H. sample = raw66_df. k = 3.
est_s2_m1_to_gH <- run_conditional_granger_var(raw66_df, c("pi_t", "g_M1", "g_H"), "g_M1", "g_H", 3)
print(est_s2_m1_to_gH)
est_s2_gH_to_m1 <- run_conditional_granger_var(raw66_df, c("pi_t", "g_M1", "g_H"), "g_H", "g_M1", 3)
print(est_s2_gH_to_m1)
est_s2_pi_to_m1 <- run_conditional_granger_var(raw66_df, c("pi_t", "g_M1", "g_H"), "pi_t", "g_M1", 3)
print(est_s2_pi_to_m1)
est_s2_m1_to_pi <- run_conditional_granger_var(raw66_df, c("pi_t", "g_M1", "g_H"), "g_M1", "pi_t", 3)
print(est_s2_m1_to_pi)

cat("\n=======================================================\n")
cat("EXACT PHASE 9E ESTIMATOR FOR SYSTEM 6 (PRE-73) AT k=3\n")
cat("=======================================================\n")
pre73_df <- df_full %>% filter(date < as.Date("1973-10-01"))
s6_vars <- c("g_SolvR_H", "g_gold", "g_e", "g_H", "pi_t")
est_s6_solv_to_gH <- run_conditional_granger_var(pre73_df, s6_vars, "g_SolvR_H", "g_H", 3)
print(est_s6_solv_to_gH)
est_s6_gH_to_solv <- run_conditional_granger_var(pre73_df, s6_vars, "g_H", "g_SolvR_H", 3)
print(est_s6_gH_to_solv)
est_s6_solv_to_ge <- run_conditional_granger_var(pre73_df, s6_vars, "g_SolvR_H", "g_e", 3)
print(est_s6_solv_to_ge)
est_s6_pi_to_solv <- run_conditional_granger_var(pre73_df, s6_vars, "pi_t", "g_SolvR_H", 3)
print(est_s6_pi_to_solv)
